services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: wagering
      POSTGRES_PASSWORD: wagering
      POSTGRES_DB: wagering
    ports:
      - '5432:5432'
    volumes:
      - wagering-pg:/var/lib/postgresql/data

volumes:
  wagering-pg:
